import { useState } from "react"
import { CheckCircle2, ScanLine, XCircle } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { voucherKiosks, voucherPackages } from "../data/voucher-data"
import type { Voucher, VoucherValidationInput, VoucherValidationResult } from "../types/voucher.types"
import { formatVoucherDateTime, getVoucherBenefitLabel, validateVoucher } from "../utils/voucher-utils"

interface VoucherValidationSimulatorProps { readonly vouchers: ReadonlyArray<Voucher>; readonly onRedeem: (voucher: Voucher, input: VoucherValidationInput) => void }
const defaultInput: VoucherValidationInput = { code: "UNIGA-7K9M2P4X", kioskId: voucherKiosks[0].id, packageId: voucherPackages[2].id, customerIdentifier: "CUST-SIM-001" }
export function VoucherValidationSimulator({ vouchers, onRedeem }: VoucherValidationSimulatorProps) {
  const [input, setInput] = useState(defaultInput); const [result, setResult] = useState<VoucherValidationResult | null>(null); const [confirmOpen, setConfirmOpen] = useState(false)
  function validate(): void { setResult(validateVoucher(input, vouchers)) }
  return <Card><CardHeader><CardTitle>Voucher Validation Simulator</CardTitle><CardDescription>Preview the rules applied by the desktop app before a session starts.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="space-y-2"><Label htmlFor="sim-code">Voucher code</Label><Input id="sim-code" className="font-mono uppercase" value={input.code} onChange={(event) => setInput((current) => ({ ...current, code: event.target.value.toUpperCase() }))} /></div><div className="space-y-2"><Label htmlFor="sim-kiosk">Kiosk</Label><Select<string> value={input.kioskId} onValueChange={(value) => value && setInput((current) => ({ ...current, kioskId: value }))}><SelectTrigger id="sim-kiosk"><SelectValue /></SelectTrigger><SelectContent>{voucherKiosks.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="sim-package">Package</Label><Select<string> value={input.packageId} onValueChange={(value) => value && setInput((current) => ({ ...current, packageId: value }))}><SelectTrigger id="sim-package"><SelectValue /></SelectTrigger><SelectContent>{voucherPackages.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="sim-customer">Customer identifier</Label><Input id="sim-customer" value={input.customerIdentifier} onChange={(event) => setInput((current) => ({ ...current, customerIdentifier: event.target.value }))} /></div></div><Button onClick={validate}><ScanLine aria-hidden="true" /> Validate Voucher</Button><div aria-live="polite">{result && (result.valid ? <Alert><CheckCircle2 aria-hidden="true" /><AlertTitle>Voucher is valid</AlertTitle><AlertDescription><p>{getVoucherBenefitLabel(result.voucher.benefit)} · {result.remainingRedemptions} redemption(s) remaining · {result.voucher.expiresAt ? `Expires ${formatVoucherDateTime(result.voucher.expiresAt)}` : "No expiration"}</p><Button className="mt-3" size="sm" onClick={() => setConfirmOpen(true)}>Continue Session</Button></AlertDescription></Alert> : <Alert variant="destructive"><XCircle aria-hidden="true" /><AlertTitle>Voucher rejected</AlertTitle><AlertDescription>{result.reason}</AlertDescription></Alert>)}</div></CardContent><AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Start session with this voucher?</AlertDialogTitle><AlertDialogDescription>This demo will record one local redemption and update the voucher usage status.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => { if (result?.valid) { onRedeem(result.voucher, input); setResult(null) } }}>Confirm and Start</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></Card>
}
