import type {
  KioskCatalogItem,
  KioskPrintHistoryItem,
  KioskWelcomeSettings,
} from "./kiosk-catalog.types"

export const kioskCatalog: ReadonlyArray<KioskCatalogItem> = [
  {
    id: "KSK-AMEHO",
    slug: "ameho",
    name: "AMEHO",
    frameCount: 10,
    license: "SAO-3Q9-CGZ",
    pricePerPrint: 35_000,
    expiresAt: "2027-01-03",
    status: "offline",
    applicationVersion: "2.1.3",
    screenOrientation: "landscape-primary",
    lastHeartbeat: "2 jam yang lalu",
    printer: { name: "DS-RX1 (2R)", status: "ready" },
    camera: { name: "Canon EOS M50", connected: false },
    paper: { capacity: 400, remaining: 283 },
  },
  {
    id: "KSK-001",
    slug: "main-studio",
    name: "Main Studio Booth",
    frameCount: 18,
    license: "KSK-8F2-MST",
    pricePerPrint: 40_000,
    expiresAt: "2027-06-30",
    status: "online",
    applicationVersion: "2.4.1",
    screenOrientation: "landscape-primary",
    lastHeartbeat: "baru saja",
    printer: { name: "DNP DS-RX1", status: "ready" },
    camera: { name: "Canon EOS M50", connected: true },
    paper: { capacity: 400, remaining: 326 },
  },
  {
    id: "KSK-002",
    slug: "sudirman",
    name: "Booth Sudirman",
    frameCount: 14,
    license: "KSK-7A4-SDM",
    pricePerPrint: 35_000,
    expiresAt: "2027-04-18",
    status: "online",
    applicationVersion: "2.4.1",
    screenOrientation: "portrait-primary",
    lastHeartbeat: "1 menit yang lalu",
    printer: { name: "DNP DS620", status: "ready" },
    camera: { name: "Sony A6400", connected: true },
    paper: { capacity: 400, remaining: 241 },
  },
  {
    id: "KSK-003",
    slug: "kemang",
    name: "Booth Kemang",
    frameCount: 12,
    license: "KSK-5C8-KMG",
    pricePerPrint: 35_000,
    expiresAt: "2027-03-12",
    status: "maintenance",
    applicationVersion: "2.3.8",
    screenOrientation: "landscape-primary",
    lastHeartbeat: "35 menit yang lalu",
    printer: { name: "DNP DS-RX1", status: "offline" },
    camera: { name: "Canon EOS M50", connected: true },
    paper: { capacity: 400, remaining: 97 },
  },
  {
    id: "KSK-004",
    slug: "senayan",
    name: "Booth Senayan",
    frameCount: 16,
    license: "KSK-9D1-SNY",
    pricePerPrint: 45_000,
    expiresAt: "2027-08-20",
    status: "online",
    applicationVersion: "2.4.1",
    screenOrientation: "portrait-primary",
    lastHeartbeat: "2 menit yang lalu",
    printer: { name: "DNP DS620", status: "ready" },
    camera: { name: "Sony A6400", connected: true },
    paper: { capacity: 400, remaining: 354 },
  },
  {
    id: "KSK-005",
    slug: "blok-m",
    name: "Booth Blok M",
    frameCount: 9,
    license: "KSK-2B6-BLM",
    pricePerPrint: 30_000,
    expiresAt: "2027-02-08",
    status: "warning",
    applicationVersion: "2.3.9",
    screenOrientation: "landscape-primary",
    lastHeartbeat: "8 menit yang lalu",
    printer: { name: "DNP DS-RX1", status: "ready" },
    camera: { name: "Canon EOS M50", connected: true },
    paper: { capacity: 400, remaining: 42 },
  },
]

export const kioskPrintHistory: ReadonlyArray<KioskPrintHistoryItem> = [
  { id: "PRT-117", occurredAt: "2026-07-14T22:55:00+07:00", type: "SESSION", copies: 1 },
  { id: "PRT-116", occurredAt: "2026-07-14T21:13:00+07:00", type: "SESSION", copies: 1 },
  { id: "PRT-115", occurredAt: "2026-07-14T20:45:00+07:00", type: "SESSION", copies: 1 },
  { id: "PRT-114", occurredAt: "2026-07-14T20:23:00+07:00", type: "SESSION", copies: 1 },
  { id: "PRT-113", occurredAt: "2026-07-14T19:28:00+07:00", type: "SESSION", copies: 1 },
  { id: "PRT-112", occurredAt: "2026-07-14T19:22:00+07:00", type: "SESSION", copies: 1 },
  { id: "PRT-111", occurredAt: "2026-07-14T19:14:00+07:00", type: "SESSION", copies: 3 },
  { id: "PRT-110", occurredAt: "2026-07-14T15:44:00+07:00", type: "REPRINT", copies: 2 },
]

export const kioskWelcomeSettings: KioskWelcomeSettings = {
  layout: "classic",
  backgroundColor: "#ffffff",
  ornamentColor: "#000000",
  borderColor: "#000000",
  textColor: "#000000",
  buttonBackgroundColor: "#000000",
  buttonTextColor: "#ffffff",
  title: "KOLASE PHOTOBOOTH",
  tagline: "Your smiles is our happiness.",
  logoHeight: 90,
  galleryAccentColor: "#000000",
  galleryBackgroundColor: "#ffffff",
  instagram: "@kolasephotobooth",
  tiktok: "@kolasephotobooth",
}

export function findKioskBySlug(slug: string | undefined): KioskCatalogItem | undefined {
  if (!slug) return undefined
  return kioskCatalog.find((kiosk) => kiosk.slug === slug)
}
